source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
#inhibit_all_warnings!

def common
	pod 'WeexSDK'
	pod 'WeexPluginLoader'
	pod 'ShareSDK3'
	pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
	
	
end

target 'WeexWXPay' do
    common
end


